# Generated by Django 5.2.9 on 2025-12-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_comment_id_alter_likedpost_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('HR', 'Hr'), ('Development', 'Dev'), ('UI/UX', 'Uiux'), ('Design', 'Design'), ('Relev/Relex', 'Relevrelex'), ('Communication', 'Comm'), ('Multimedia', 'Multimedia')], max_length=15),
        ),
    ]
