# Generated by Django 5.2.9 on 2025-12-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_comment_id_alter_departmentsubscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user_images/default-profile.svg', null=True, upload_to='user_images/'),
        ),
    ]
